dist: trusty
language: python
before_script:
  - ansible --version
  - openstack --version
script: ./check.sh
deploy:
  - provider: script
    script: ./deploy.sh
    skip_cleanup: true
    on:
      repo: aeternity/infrastructure
      branch: master
  - provider: script
    script: ./deploy.sh
    skip_cleanup: true
    on:
      repo: aeternity/infrastructure
      branch: fix/travis-deploy
cache:
  directories:
    - $HOME/.cache/pip
