dist: trusty
language: python
install: pip install --user -r requirements.txt
before_script:
  - ansible --version
  - openstack --version
script:
  - ./check.sh
  - ./deploy.sh
deploy:
  - provider: script
    script: ./deploy.sh
    skip_cleanup: true
    on:
      repo: aeternity/infrastructure
      branch: master
cache:
  directories:
    - $HOME/.cache/pip
